// Auto-generated at build time
export const propertyRoutes = [
  "/real-estate/properties/joyas-del-mar-seven-condo-residential-complex/",
  "/real-estate/rentals/casa-bermejo/",
  "/real-estate/properties/el-pedregal-san-carlos/",
  "/real-estate/properties/sea-escape-beachfront-condos/",
  "/real-estate/properties/sea-escape-beachfront-condos/",
  "/real-estate/properties/vistas-del-country-san-carlos/",
  "/real-estate/properties/la-rioja-residencial-hermosillo/",
  "/real-estate/rentals/villas-de-solimar-san-carlos/",
  "/real-estate/rentals/casa-olivia/",
  "/real-estate/rentals/casa-jade/",
  "/real-estate/rentals/casa-estelamar/",
  "/real-estate/rentals/casa-arena/",
  "/real-estate/properties/costa-del-mar/",
  "/real-estate/rentals/casa-maria-costa-real/",
  "/real-estate/rentals/casa-marenka-country-club/",
  "/real-estate/properties/sector-creston/",
  "/real-estate/properties/villa-california-residencial/",
  "/real-estate/rentals/casa-sunset/",
  "/real-estate/rentals/casa-marino/",
];
