// Auto-generated at build time
export const propertyRoutes = [
  "/properties/joyas-del-mar-seven-condo-residential-complex/",
  "/rentals/casa-bermejo/",
  "/properties/el-pedregal-san-carlos/",
  "/properties/sea-escape-beachfront-condos/",
  "/properties/sea-escape-beachfront-condos/",
  "/properties/vistas-del-country-san-carlos/",
  "/properties/la-rioja-residencial-hermosillo/",
  "/rentals/villas-de-solimar-san-carlos/",
  "/rentals/casa-olivia/",
  "/rentals/casa-jade/",
  "/rentals/casa-estelamar/",
  "/rentals/casa-arena/",
  "/properties/costa-del-mar/",
  "/rentals/casa-maria-costa-real/",
  "/rentals/casa-marenka-country-club/",
  "/properties/sector-creston/",
  "/properties/villa-california-residencial/",
  "/rentals/casa-sunset/",
  "/rentals/casa-marino/",
];
