// Auto-generated at build time
export const propertyRoutes = [
  "bienes-raices/properties/joyas-del-mar-seven-condo-residential-complex/",
  "bienes-raices/rentals/casa-bermejo/",
  "bienes-raices/properties/el-pedregal-san-carlos/",
  "bienes-raices/properties/sea-escape-beachfront-condos/",
  "bienes-raices/properties/sea-escape-beachfront-condos/",
  "bienes-raices/properties/vistas-del-country-san-carlos/",
  "bienes-raices/properties/la-rioja-residencial-hermosillo/",
  "bienes-raices/rentals/villas-de-solimar-san-carlos/",
  "bienes-raices/rentals/casa-olivia/",
  "bienes-raices/rentals/casa-jade/",
  "bienes-raices/rentals/casa-estelamar/",
  "bienes-raices/rentals/casa-arena/",
  "bienes-raices/properties/costa-del-mar/",
  "bienes-raices/rentals/casa-maria-costa-real/",
  "bienes-raices/rentals/casa-marenka-country-club/",
  "bienes-raices/properties/sector-creston/",
  "bienes-raices/properties/villa-california-residencial/",
  "bienes-raices/rentals/casa-sunset/",
  "bienes-raices/rentals/casa-marino/",
];
